Create make:datagrid command
wdev-rs/laravel-datagrid pull request #12
Opened 2022-10-06 13:38 UTC by thebatclaudio

Close issue #11

2022-10-11 12:55 UTC, daniel-werner requested changes
Thanks for the PR, works great! I'd like to change some minor things, if you could address those.

2022-10-11 12:55 UTC, daniel-werner commented on src/Console/Commands/MakeDataGrid.php
> +                list($label, $field) = explode(":", $field);
Could you please change  the order to `list($field, $label)`

2022-10-11 12:55 UTC, daniel-werner commented on src/Console/Commands/MakeDataGrid.php
> +        $model = $this->option("model");
Would it be possible to generate a use statement to the top of the created datagrid file for the given model with the default namespace, eg: use App\Models\{model given as argument}?

2022-10-12 07:39 UTC, thebatclaudio commented
Hello @daniel-werner, 
I just made the changes that you requested! Let me know if it's ok

2022-10-12 07:58 UTC, daniel-werner commented
@thebatclaudio Changes are fine, merging it. Thanks!

2022-10-12 07:58 UTC, merged